### ISSUE TITLE
typecatcher for fedora?

### ISSUE THREAD

**Issue by shivarajnaidu** [andrewsomething/typecatcher#1]
typecatcher is amazing app for linux.. but how to install it on fedora and other Linux os s?
is there any way to install typecatcher other than Ubuntu and deb based systems.?

**Comment by mmstick** [comment]
[Arch Linux has support.](https://aur.archlinux.org/packages/typecatcher/) Packaging would be pretty stupid simple if someone that uses Fedora or any other OS would want to package it:

```sh
python3 setup.py build
python3 setup.py install --root=$pkgdir --optimize=1
install -dm755 ${pkgdir}/usr/share/licenses/${pkgname}/
install -Dpm644 COPYING ${pkgdir}/usr/share/licenses/${pkgname}/
install -dm755 ${pkgdir}/usr/share/doc/${pkgname}/
install -Dpm644 AUTHORS ${pkgdir}/usr/share/doc/${pkgname}/
```

Just ensure that you have these dependencies installed:

python3 python-distutils-extra python-gobject yelp

**Comment by shivarajnaidu** [comment]
Sorry .. I am Newbie .. Don't know much about packaging stuff .. However Thanks for your kind reply
@mmstick

**Comment by Thetoxicarcade** [comment]
same.

**Comment by johjeff** [comment]
Hello,

I am on Fedora 26 and am attempting to build and install typecatcher. Here is my Python version: 

python3 --version
Python 3.6.1 :: Anaconda custom (64-bit)

Anaconda Python distribution is located in /opt/anaconda3. I installed yelp and python3-gobject with 'pip', and installed  python-distutils-extra via GIT.

I succeeded in the build/install, but when I try to run typecatcher, I get the following error:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/typecatcher.py", line 46, in <module>
    import typecatcher
  File "/opt/anaconda3/lib/python3.6/site-packages/typecatcher/__init__.py", line 21, in <module>
    from typecatcher_lib import Application
  File "/opt/anaconda3/lib/python3.6/site-packages/typecatcher_lib/__init__.py", line 22, in <module>
    from . helpers import set_up_logging
  File "/opt/anaconda3/lib/python3.6/site-packages/typecatcher_lib/helpers.py", line 23, in <module>
    import gi
  File "/opt/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'


Any chance someone can point me in the right direction? It would be nice to have this application in a snap, flatpak, or appimage package.

Thanks.

**Comment by mmstick** [comment]
May be best if we just rewrite this in an actual systems language. Rust rewrite candidate, perhaps? I could probably look into it.

**Comment by andrewsomething** [comment]
@johjeff How did you install `gi`? 

I'll look into providing a snap or flatpack. I do not regularly use a Fedora system nor am I versed in the art of RPM packaging, so I have no intentions to package it as an RPM myself. Thought, I'm happy to help anyone who is interested in doing so.

**Comment by mmstick** [comment]
@andrewsomething Python software comes with a whole sleuth of issues. Runtime bugs, compatibility issues, over-reliance on pip, performance issues, etc. So, lets save the planet and rewrite this in a proper compiled lang that won't require snaps or flatpaks for distribution.

**Comment by johjeff** [comment]
gi comes with python3-gobjects I believe. I installed in Anaconda using PIP, but I installed in the OS with DNF(rpm). So, rather than go through the build steps above, I deleted my previous clone, and recloned the project. Then, I simply ran the executable in 'bin' and it worked. That is assuming all your dependencies are in place. So, the question is what are all the dependencies, both Python and system. To be honest I haven't created a distribution independent package yet, but I believe they package up all the dependencies in the package. That makes it much bigger, but should allow it to run on any platform.

**Comment by johjeff** [comment]
I just checked from Anaconda and it runs there too after manually installing those deps with PIP.

**Comment by probonopd** [comment]
> It would be nice to have this application in a snap, flatpak, or __appimage__ package.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by millerthegorilla** [comment]
Python 3 is causing the problem @johjeff 
The program is written using python2.7.  You may need to use update-alternatives  or run from the command line using /usr/bin/python2.7 typecatcher.

**Comment by millerthegorilla** [comment]
Actually, it doesn't seem like typecatcher will build for fedora as fedora doesn't have an equivalent to distutils-extra.

**Comment by q2dg** [comment]
In fact, this project seems pretty abandoned...
