### ISSUE TITLE
error with python-3.7

### ISSUE THREAD

**Issue by soloturn** [andrewsomething/typecatcher#12]
there is a comment here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890754

From: Adrian Bunk <bunk@debian.org>
To: Debian Bug Tracking System <submit@bugs.debian.org>
Subject: python3.6 3.6.4-4 makes typecatcher FTBFS
Date: Sun, 18 Feb 2018 14:27:57 +0200
Package: python3.6
Version: 3.6.4-4
Severity: serious
Control: affects -1 src:typecatcher

https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/typecatcher.html

...
I: pybuild base:184: python3.6 setup.py config 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Traceback (most recent call last):
  File "setup.py", line 144, in <module>
    cmdclass={'install': InstallAndUpdateDataDirectory}
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 405, in __add_imports
    if alias.name and __external_mod(cur_module, alias.name, attrs):
  File "/usr/lib/python3/dist-packages/DistUtilsExtra/auto.py", line 377, in __external_mod
    return 'dist-packages' in mod.__file__ or 'site-packages' in mod.__file__ or \
TypeError: argument of type 'NoneType' is not iterable
E: pybuild pybuild:283: configure: plugin distutils failed with: exit code=1: python3.6 setup.py config 
dh_auto_configure: pybuild --configure -i python{version} -p 3.6 returned exit code 13
make: *** [debian/rules:6: build] Error 25

Downgrading the python3.6 packages to 3.6.4-3 fixes the FTBFS.

same happens on arch linux AUR, https://aur.archlinux.org/packages/typecatcher/

**Comment by Tubbles** [comment]
I just ran into this problem. Anybody has any working solution or a clue as to what is wrong?

**Comment by signoredellarete** [comment]
I think you are launching the program from the command line, but typecatcher needs to use a graphical display. You can launch it by setting the correct display, for example:

export DISPLAY=:0

and then

typecatcher

**Comment by oliverpool** [comment]
Apparently the issue can be fixed by switching to `setuptools` : https://github.com/jeromerobert/pdfarranger/issues/31#issuecomment-440026266 (https://github.com/jeromerobert/pdfarranger/commit/ebf6cd0028614595bcbef5c1151b5038e5b00ca0).

Unfortunately my python knowledge is probably not good enough to fix this...
