### ISSUE TITLE
OpenPGP Debian buster

### ISSUE THREAD

**Issue by Lewiscowles1986** [andrewsomething/typecatcher#13]
Repo, you're directing people to use is broken for Debian buster

```
sudo add-apt-repository ppa:andrewsomething/typecatcher
 TypeCatcher allows you to search, browse, and download Google webfonts for off-line use. You can preview fonts with adjustable size and text.

https://launchpad.net/typecatcher
 More info: https://launchpad.net/~andrewsomething/+archive/ubuntu/typecatcher
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp6x2xxmb7/pubring.gpg' created
gpg: /tmp/tmp6x2xxmb7/trustdb.gpg: trustdb created
gpg: key CA1F91146F087E5A: public key "Launchpad PPA for Andrew Starr-Bochicchio" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.ssh'
```

It could relate to #12 but the error message is different and is at a different stage.

**Comment by Lewiscowles1986** [comment]
## Workaround found

```
sudo apt-get install python3-distutils-extra
git clone https://github.com/andrewsomething/typecatcher.git
cd typecatcher
sudo python3 setup.py install
```

This was all I needed

**Comment by litebringer** [comment]
did not help at all , getting same error

**Comment by Lewiscowles1986** [comment]
@litebringer can you share what you typed as well as the output of `uname -a` and `lsb -release`?
