### ISSUE TITLE
Fails to build on Garuda Linux

### ISSUE THREAD

**Issue by binarydepth** [andrewsomething/typecatcher#15]
Build error:

```(setup.py:669002): Gtk-WARNING **: 09:00:16.303: Theme parsing error: gtk-dark.css:6342:10: 'height' is not a valid property name
Traceback (most recent call last):
  File "/home/makepkg/typecatcher/src/typecatcher-0.3/setup.py", line 135, in <module>
    DistUtilsExtra.auto.setup(
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 98, in setup
    __requires(attrs, src_all)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 471, in __requires
    __add_imports(imports, s, attrs)
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 405, in __add_imports
    if alias.name and __external_mod(cur_module, alias.name, attrs):
  File "/usr/lib/python3.9/site-packages/DistUtilsExtra/auto.py", line 377, in __external_mod
    return 'dist-packages' in mod.__file__ or 'site-packages' in mod.__file__ or \
TypeError: argument of type 'NoneType' is not iterable
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Lewiscowles1986** [comment]
I'm unsure which distribution you are using, but perhaps this is an issue with your distutils.

I Used the following command in #13 

```
sudo apt-get install python3-distutils-extra
```

Not knowing Garuda Linux, I cannot comment on the package manager it uses, or if it would be better to manually install the package; but the two issues look very closely related.
